export const colors = {
  primary: "#E8560C",
  adobeOrange: "#ea966b",
  bgChatScreen: "#eebca3",
  bgSenderMsg: "#dcf7c5",
  bgParticipantMsg: "#fafafa",
  bgScreen02: "#efeff4",
  lavenderMist: "#EDEDFF",
  text: "#4e4e4",
  eclipseGray: "#3C3C43",
  coolGray: "#c6c6cc",
  textMessage: "#8E8E93",
  mediumGray: "#8b8989",
  snowWhite: "#fffcfc",
  culturedPearl: "#f6f6f6",
  black: "#000",
  white: "#fff",
  amber: "#fbb500",
  lightGray: "#bbbbc0",
  seaTeal: "#07ad9f",
  skyBlue: "#397afe",
  limeGreen: "#4bd763",
  coralRed: "#ff3b2f",
  infoBlue: "#4ba0fe",
  magentaRed: "#ff2c55",
  cyberPink: "#ec72d7",
};
